# -*- coding: utf-8 -*-
"""PizzaProjesi1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ID9Lt5RjWE-XUQi64asa3YGUHJhWOkcP
"""

#Başlamadan önce kütüphaneleri tanımlayıp modülleri çağırma işlemimizi yapıyoruz.
import csv
import datetime
import sqlite3

# Bir tane veritabanı dosyası oluşturdum. Ama buraya eklerken böyle bir dosya yok diyor. Sürekli hata alıyorum nedenini bilmediğim bir şekilde. #
# Derslerde dosya oluşturma anlatılmadı. Ben python'da sıfırım diyebilirim. Elimden geldiği kadar yapmaya çalıştım. #
# Dosya çalışmazsa aşağıdaki kodları denemenizi rica ediyorum. Aşağıdakiler çalışıyor ama veritabanı dosyasını yapamadım sanırım. #

# Burada csv dosyası oluşturduk ve kullanıcıdan bilgilerini aldık. 
con=sqlite3.connect("‪Müşteribilgileri.csv")
cursor=con.cursor()
def TabloOlustur():
  cursor.execute("CREATE TABLE IF NOT EXISTS musteriler(kullanıcı_adi TEXT,TC_kimlik_numarasi INTEGER,kredi_karti_numarasi INTEGER,kredi_karti_sifresi INTEGER,siparis_aciklamasi TEXT,siparis_zamani DATE)")
  con.commit()
TabloOlustur()
def deger_ekle(kullanıcı_adi,TC_kimlik_numarasi,kredi_karti_numarasi,kredi_karti_sifresi,siparis_aciklamasi,siparis_zamani):
cursor.execute("INSERT INTO musteriler VALUES(?,?,?,?,?,?)",(kullanıcı_adi,TC_kimlik_numarasi,kredi_karti_numarasi,kredi_karti_sifresi,siparis_aciklamasi,siparis_zamani))
con.commit()
kullanıcı_adi=input("Kullanıcı adınız:")
TC_kimlik_numarasi=int(input("TC kimlik numaranız:"))
kredi_karti_numarasi=int(input("Kredi kartı numaranız:"))
kredi_karti_sifresi=int(input("Kredi kartı şifreniz:"))
siparis_aciklamasi=input("Sipariş açıklaması:")
siparis_zamani=input("Siparis zamanı:")
break

deger_ekle(kullanıcı_adi,TC_kimlik_numarasi,kredi_karti_numarasi,kredi_karti_sifresi,siparis_aciklamasi,siparis_zamani)
con.close()

# Burada dosyamızın içine aşağıdaki bilgileri yazdık.
with open("C:\\Users\\Lenovo\\Desktop\\Müşteribilgileri.csv","w") as dosyam:
  yazıcı = csv.writer(dosyam)
  yazıcı.writerow(["Elif","12547896325","5478 5988 6541 2254","2224","Pizzalar","17.02.2023"])
  yazıcı.writerow(["Esra","14587965523","8752 6548 7546 9322","8887","Pizza","10.02.2023"])
  yazıcı.writerow(["Fatih","25447788541","1452 2325 6547 7895","5587","Akşam Pizzası","20.12.2022"])
  yazıcı.writerow(["Burak","11665447875","7485 5547 7878 9558","7854","Pizza","10.10.2022"])
  yazıcı.writerow(["Melisa","12225449987","1245 2236 6588 9754","6522","Atıştırmalık","15.02.2023"])
  yazıcı.writerow(["Ecem","55566333224","2144 5236 6565 9874","1234","Pizza","31.12.2022"])
  yazıcı.writerow(["Ahmet","12345678912","3225 5447 7845 5122","5423","Pizza","01.01.2023"])
  yazıcı.writerow(["Efe","55447875596","2145 5565 2123 9987","1244","Pizzalar","26.12.2022"])
  yazıcı.writerow(["Ozan","33254122565","7458 8845 9875 2132","9554","Pizza","12.03.2023"])
  yazıcı.writerow(["Kiraz","44788552163","1236 5214 8795 6845","8755","Pizzalar","03.03.2023"])
  yazıcı.writerow(["Okan","98795864123","2147 8556 2365 9875","3652","Pizza Kaçamağı","20.02.2023"])

# Aşağıda oluşturduğum veritabanı dosyasını okumasını istedim.
musteriler=open("‪Müşteribilgileri.csv","r")     #C:\Users\Ayaz\Desktop\Bootcamp Proje\müşteriler.csv","r
print("Kullanıcı adınızı giriniz:")
kullanici_adi=input()
okuyucu=csv.reader(musteriler)
content=next(okuyucu)

# Menu isimli bir dosya açtık ve içine menümüzü yazdık.
menu=open("menu.txt", "w")  # Burada menu adlı bir dosya açtık ve içine pizzalar ve sosları yazdık.
menu.write("Lütfen bir Pizza Tabanı ve istediğiniz sosu/sosları seçiniz: \nPizzalar: \n****************************** \n1: Klasik Pizza (25 ₺) \n2: Margarita Pizza (35 ₺) \n3: TürkPizza (30 ₺) \n4: Sade Pizza (20 ₺) \nSoslar: \n****************************** \n1.1: Zeytin (6 ₺) \n1.2: Mantarlar (8 ₺) \n1.3: Keçi Peyniri (15 ₺) \n1.4: Et (12 ₺) \n1.5: Soğan (6 ₺) \n1.6: Mısır (10 ₺) \nTeşekkür ederiz!")
menu.close()  # menu dosyasını kapattık.

# Burada menu dosyasını okuduk. Ekrana menümüzü basacak.
with open("menu.txt","r") as f:  
  print(f.read())

def main(menu):
  class Pizza:  # Burada Pizza adlı bir üst sınıf tanımladık. Pizza sınıfı tanımladık.
    def __init__(self):
      self.description = "PizzaStar"    # Pizza dükkanımızın adı.Pizzanın açıklaması
      self.cost = 0.0          # Pizzanın maliyetini öğrendiğimiz kısım.

    def pizza_adi(self):    # pizza adını self yaptık. Böylelikle sürekli pizzanın adını yazmak zorunda kalmayacağız.
      return self.description       

    def pizza_fiyati(self):   # Burada pizzanın maliyetini yazıyoruz. Maliyetini göründüğü kısmdır.
      return self.cost

  class KlasikPizza(Pizza):       # Klasik Pizza isimli pizzamızı tanımladık.
    def __init__(self):
      self.description = "Klasik Pizza"  # Pizzamızın adı
      self.cost = 25.0          # Pizzamızın fiyatı

  class MargaritaPizza(Pizza):   # Margarita isimli pizzamızı tanımladık. 
    def __init__(self):
      self.description = "Margarita Pizza"  # Burada pizzanın adını yazdık.
      self.cost = 35.0             # Pizzamızın maliyetini yazdık.

  class TurkPizza(Pizza):     # Türkpizza isimli pizzamızı tanımladık.
    def __init__(self):
      self.description = "Türk Pizza"  # Pizzamızın isminin açıklaması
      self.cost = 30.0        # Pizzamızın fiyatı.

  class SadePizza(Pizza):       # Sade pizzamızı tanımladık. Bu alan Sade pizzanın özelliklerinin gösterildiği alandır, fonksiyondur.
    def __init__(self):
      self.description = "Sade Pizza"     # Pizzamızın ismini yazdık.
      self.cost = 20.0           # Pizzamızın maliyeti.

  # Pizzaya malzeme eklemek için bir dekoratör sınıfı tanımlıyoruz.
  # Dekoratör üst sınıfı oluşturup soslarımızı alt sınıf olarak tanımlayıp fiyatını ve açıklamasını giriyoruz.
  class Decorator(Pizza):     
    def __init__(self, component):
      self.component = component           

    def get_cost(self):
      return self.component.get_cost() + Pizza.get_cost(self)
      # Ek malzeme ile pizzanın maliyetini alıyoruz.
    def get_description(self):
      return self.component.get_description() + ' ' + Pizza.get_description(self)
      # Burada ek malzemeli pizzanın açıklamasını alıyoruz.

# Farklı sos türleri için alt sınıfları tanımlıyoruz.
  class Zeytin(Decorator):     # Üst sınıfımız Decorator. Alt sınıfımızın zeytin. Zeytini alt sınıf olarak tanımlıyoruz.
    def __init__(self, component):
      self.component = component
      self.description = "Zeytin"   # sosumuzun adı
      self.cost = 6.0      # sosumuzun fiyatı

  class Mantarlar(Decorator):                          
    def __init__(self, component):
      self.component = component
      self.description = "Mantarlar"   # Burada sosumuzun adını girdik.
      self.cost = 8.0                  # Burada sosumuzun maliyetini girdik.

  class KeçiPeyniri(Decorator):
    def __init__(self, component):
      self.component = component
      self.description = "Keçi Peyniri"    # Burada sosumuzun adını girdik.
      self.cost = 15.0                     # Burada sosumuzun maliyetini girdik.

  class Et(Decorator):
    def __init__(self, component):
      self.component = component
      self.description = "Et"          # Burada sosumuzun adını girdik.
      self.cost = 12.0                 # Burada sosumuzun maliyetini girdik.

  class Soğan(Decorator):
    def __init__(self, component):
      self.component = component       
      self.description = "Soğan"       # Burada sosumuzun maliyetini girdik.
      self.cost = 6.0                  # Burada sosumuzun maliyetini girdik.

  class Mısırlar(Decorator):
    def __init__(self, component):
      self.component = component
      self.description = "Mısırlar"     # Burada sosumuzun maliyetini girdik.
      self.cost = 10.0                  # Burada sosumuzun maliyetini girdik.


ToplamUcret=0
while True:
  pizza_secimi=input("Lütfen istediğiniz pizzanın numarasını seçiniz:")
  adet=int(input("Kaç adet istiyorsunuz?:"))
  if pizza_secimi == "1":         # Eğer kullanıcının pizza seçimi 1 numaralı pizza ise 1 numaralı pizzanın ücretini kaç adet aldıysa onunla çarpıp toplam ücreti belirleyecek.
    ToplamUcret += adet * 25
  elif pizza_secimi == "2":       #Eğer kullanıcının pizza seçimi 2 numaralı pizza ise 2 numaralı pizzanın ücretini kaç adet aldıysa onunla çarpıp toplam ücreti belirleyecek.
    ToplamUcret += adet * 35
  elif pizza_secimi == "3":       #Eğer kullanıcının pizza seçimi 3 numaralı pizza ise 3 numaralı pizzanın ücretini kaç adet aldıysa onunla çarpıp toplam ücreti belirleyecek.
    ToplamUcret += adet * 30
  elif pizza_secimi == "4":       #Eğer kullanıcının pizza seçimi 4 numaralı pizza ise 4 numaralı pizzanın ücretini kaç adet aldıysa onunla çarpıp toplam ücreti belirleyecek.
    ToplamUcret += adet * 20
  sor=input("Pizzalar bölümünden başka bir şey istermisiniz? (Evet/Hayır):")
  if sor == "Hayır":
    print(":)")     # Bu bölümden başka bir şey istemezse ekrana gülücük çıktısını verip sosların seçimine geçilecek.

  sos_secimi=input("Lütfen istediğiniz sosun/sosların numarasını da seçiniz:")
  adet=int(input("Kaç adet istiyorsunuz?:"))
  if sos_secimi == "1.1":
    ToplamUcret += adet * 6      # Kullanıcı 1.1 numaralı sosu seçtiyse sosun fiyatı ile kaç adet aldıysa o fiyat çarpılıp toplam ücret hesaplanacak.
  elif sos_secimi == "1.2":
    ToplamUcret += adet * 8      # Kullanıcı 1.2 numaralı sosu seçtiyse sosun fiyatı ile kaç adet aldıysa o fiyat çarpılıp toplam ücret hesaplanacak.
  elif sos_secimi == "1.3":
    ToplamUcret += adet * 15     # Kullanıcı 1.3 numaralı sosu seçtiyse sosun fiyatı ile kaç adet aldıysa o fiyat çarpılıp toplam ücret hesaplanacak.
  elif sos_secimi == "1.4":
    ToplamUcret += adet * 12     # Kullanıcı 1.4 numaralı sosu seçtiyse sosun fiyatı ile kaç adet aldıysa o fiyat çarpılıp toplam ücret hesaplanacak.
  elif sos_secimi == "1.5":
    ToplamUcret += adet * 6      # Kullanıcı 1.5 numaralı sosu seçtiyse sosun fiyatı ile kaç adet aldıysa o fiyat çarpılıp toplam ücret hesaplanacak.
  elif sos_secimi == "1.6":
    ToplamUcret += adet * 10     # Kullanıcı 1.6 numaralı sosu seçtiyse sosun fiyatı ile kaç adet aldıysa o fiyat çarpılıp toplam ücret hesaplanacak.
  sor=input("Soslar bölümünden başka bir şey ister misiniz? (Evet/Hayır):") 
  if sor == "Hayır":             # Cevabı hayır ise seçtiği pizzatabanı ve sosların fiyatları toplanıp müşterinin toplam ücreti ekrana yazdırılır.
    print("Toplam Ücret:",ToplamUcret,"₺")
    print("Bizi seçtiğiniz için teşekkür ederiz. Yeniden bekleriz. Güle Güle :)")  # En son bu cümle ekrana verilecek ve break ile döngü kırılacak ve sipariş alma işlemi son bulacak.
    break